version: '3.8'

services:
  app:
    # 选择一个包含git的基础镜像，或者在构建时安装git
    image: node:18-alpine
    container_name: vehicle-management-app
    working_dir: /app
    ports:
      - "3000:5000"  # 直接将容器5000端口映射到主机3000端口，简化访问
    volumes:
      - .:/app  # 确保当前目录正确挂载到容器的/app目录
      - node_modules:/app/node_modules  # 避免本地node_modules与容器冲突
      - ./uploads:/app/uploads  # 确保上传目录正确挂载
    environment:
      - MONGODB_URI=mongodb://admin:password@db:27017/vehicle-management?authSource=admin
      - JWT_SECRET=your-secret-key
      - UPLOAD_DIR=/app/uploads
      - PORT=5000
    depends_on:
      - db
    # 优化构建命令，先检查文件是否存在，然后安装依赖
    command: sh -c "echo '查看当前目录内容...' && ls -la && echo '检查package.json是否存在...' && if [ -f /app/package.json ]; then apk add --no-cache git && npm install -g pnpm && pnpm install && pnpm build && pnpm start; else echo '错误: 未找到package.json文件，检查卷挂载配置'; ls -la /; fi"
    
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: vehicle-management-db
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: always
    
volumes:
  node_modules:  # 创建named volume避免卷挂载冲突